_wandb:
    value:
        cli_version: 0.25.0
        e:
            8rhkgs0a2q5f6ekuqk5133a058yuec77:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: /Users/hazelhandrata/Developer/monkeylimitsML/category_model_tf_idf.ipynb
                codePathLocal: category_model_tf_idf.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "194048032768"
                email: hazelhandrata@gmail.com
                executable: /opt/anaconda3/envs/machinelearning/bin/python
                git:
                    commit: 1d891ad9796c01fc92dd7e47204a6441f3672134
                host: customer.krypt.com
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/hazelhandrata/Developer/monkeylimitsML/category_model_tf_idf.ipynb
                python: CPython 3.13.11
                root: /Users/hazelhandrata/Developer/monkeylimitsML
                startedAt: "2026-02-21T08:38:53.415903Z"
                writerId: 8rhkgs0a2q5f6ekuqk5133a058yuec77
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": darwin-arm64
char_analyzer:
    value: char_wb
char_min_df:
    value: 2
char_ngram_range:
    value: (3, 5)
char_sublinear_tf:
    value: true
clf_C:
    value: 1
clf_class_weight:
    value: balanced
clf_max_iter:
    value: 2000
clf_solver:
    value: lbfgs
dataset_total_rows:
    value: 1268
n_classes:
    value: 10
random_state:
    value: 42
test_ratio:
    value: 0.3
test_size:
    value: 381
train_size:
    value: 887
word_max_features:
    value: 10000
word_min_df:
    value: 2
word_ngram_range:
    value: (1, 2)
word_sublinear_tf:
    value: true
